document.writeln("  <script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"ca-pub-5232302326603171\";");
document.writeln("\/* չʾ200&#42;200 *\/");
document.writeln("google_ad_slot = \"5648818828\";");
document.writeln("google_ad_width = 200;");
document.writeln("google_ad_height = 200;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");
